-- =============================================================================
-- Eternal Life Hospice — Field Outreach Tracker
-- Data-only export from the original Replit (main marketing-site project)
-- Re-verified: 2026-08-26
-- =============================================================================
-- HOW TO USE
-- ----------
-- 1. In the standalone tracker Replit, apply its canonical schema.sql first.
-- 2. Run this file: psql $DATABASE_URL < visits-export.sql
-- 3. This verified export has no INSERT statements because the source had
--    zero visits and zero visit photos. It is intentionally safe as a no-op.
--
-- schema.sql is the only source of destination DDL. Keeping DDL out of this
-- file prevents a stale export from creating a subtly different visits table.
-- See migration-verification.md for the source counts and destination checks.
-- =============================================================================

-- ── Canonical field mapping ──────────────────────────────────────────────────
-- visits.id          → visits.id (preserved when rows exist)
-- visits.company     → visits.company
-- visits.category    → visits.category
-- visits.address     → visits.address
-- visits.city        → visits.city
-- visits.county      → visits.county
-- visits.visit_date  → visits.visit_date
-- visits.contact_*   → visits.contact_* (name, title, email, phone)
-- visits.materials   → visits.materials (JSONB)
-- visits.notes       → visits.notes
-- visits.owner       → visits.owner
-- visits.follow_up_due → visits.follow_up_due
-- visits.followup_status → visits.followup_status
-- visits.attested    → visits.attested
-- visits.created_by/created_at/updated_at → same destination columns
-- visit_photos.*     → visit_photos.*; visit_id remains the visits FK
--
-- The source database also has a legacy follow_up_method column. It is not
-- present in the standalone schema and had no values to migrate in this
-- zero-row export.

-- ── Verified data status ─────────────────────────────────────────────────────
-- visits: 0 rows
-- visit_photos: 0 rows
-- No INSERT statements are required. The destination sequences start at 1.

-- ── Future export query (run against the retired source only if needed) ─────
-- SELECT 'INSERT INTO visits (id,company,category,address,city,county,visit_date,' ||
--        'contact_name,contact_title,contact_email,contact_phone,materials,notes,' ||
--        'owner,follow_up_due,followup_status,attested,created_by,created_at,updated_at)' ||
--        ' OVERRIDING SYSTEM VALUE VALUES (' ||
--        id || ',' || quote_nullable(company) || ',' || quote_nullable(category) || ',' ||
--        quote_nullable(address) || ',' || quote_nullable(city) || ',' ||
--        quote_nullable(county) || ',' || quote_nullable(visit_date::text) || ',' ||
--        quote_nullable(contact_name) || ',' || quote_nullable(contact_title) || ',' ||
--        quote_nullable(contact_email) || ',' || quote_nullable(contact_phone) || ',' ||
--        quote_nullable(materials::text) || ',' || quote_nullable(notes) || ',' ||
--        quote_nullable(owner) || ',' || quote_nullable(follow_up_due::text) || ',' ||
--        quote_nullable(followup_status) || ',' || attested || ',' ||
--        quote_nullable(created_by::text) || ',' || quote_nullable(created_at::text) || ',' ||
--        quote_nullable(updated_at::text) || ');'
-- FROM visits ORDER BY id;
--
-- For visit photos, use pg_dump or a parameterized script to preserve BYTEA
-- values. Do not hand-edit binary data into this SQL file.