# Rename this file to .replit in your new Replit project

run = "npm start"

[nix]
channel = "stable-24_05"

[[ports]]
localPort = 5000
externalPort = 80

[deployment]
build = ["sh", "-c", "npm ci --no-audit --no-fund && npm test"]
run = ["sh", "-c", "npm start"]
deploymentTarget = "cloudrun"
