// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/elh-google-reviews/Current.tsx": () => import("../components/mockups/elh-google-reviews/Current.tsx"),
  "./components/mockups/elh-google-reviews/PremiumEditorial.tsx": () => import("../components/mockups/elh-google-reviews/PremiumEditorial.tsx")
};
