import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Activity, AlertCircle, ArrowUpRight, BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronDown, ChevronRight, CircleDot, Database, FileCheck2, FileText, Globe2, HeartHandshake, LayoutDashboard, Menu, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, TrendingUp, Users, X } from "lucide-react";
import { emailCampaigns, journalArticles, type JournalArticle } from "./contentData";
import "./hub.css";

type Item = { id:string; title:string; type:string; date:string; owner:string; status:"Needs review"|"Approved"|"Scheduled"|"Draft"|"Published"; excerpt:string; source?:JournalArticle; emailIndex?:number };
type Report = { live:boolean; generatedAt?:string; errors?:string[]; period?:{startDate:string;endDate:string}; metrics?:{sessions:number;keyEvents:number;searchClicks:number;impressions:number;ctr:number;averagePosition:number}; trend?:{date:string;sessions:number}[]; landingPages?:{page:string;sessions:number}[]; queries?:{query:string;clicks:number;impressions:number;position:number}[] };
const groups = [
  {name:"Executive", sub:"Enterprise performance", icon:LayoutDashboard, items:[["Executive Overview","Overview"],["Census Performance","Census"],["Referral Performance","Referral"],["Marketing Performance","Marketing"],["Growth Outlook","Outlook"]]},
  {name:"Marketing Performance", sub:"Visibility · acquisition · conversion", icon:TrendingUp, items:[["SEO","SEO"],["Website","Website"],["Calls & Conversions","Calls"],["Google Business Profile","GBP"],["Social Performance","Social"],["Email Performance","EmailsPerformance"],["Journal Performance","JournalPerformance"],["Care Brief Performance","CareBriefPerformance"],["Advertising","Advertising"],["Backlinks & PR","Backlinks"]]},
  {name:"Referral Performance", sub:"Relationships · pipeline · conversion", icon:HeartHandshake, items:[["Referral Overview","Referral"],["Referral Sources","ReferralSources"],["Partner Movement","PartnerMovement"]]},
  {name:"Census", sub:"Admissions · movement · trends", icon:Activity, items:[["Census Overview","Census"],["Census Trends","CensusTrends"]]},
  {name:"Expansion", sub:"Markets · penetration · opportunity", icon:Globe2, items:[["Market Overview","Expansion"],["Growth Hot Zones","HotZones"],["Opportunity Zones","Opportunity"]]},
  {name:"Attribution", sub:"Sources · conversion · contribution", icon:BarChart3, items:[["Attribution Framework","Attribution"]]},
  {name:"Intelligence", sub:"Patterns · opportunities · alerts", icon:Sparkles, items:[["Wins / Watch / Opportunity","Intelligence"]]},
];
const utility = [["Data Connections","Connections"],["Reporting Health","Health"],["Change Log","ChangeLog"],["KPI Dictionary","Definitions"]];
const studio = [["Eternal Journal","Journal"],["Email","Emails"],["Eternal Care Brief","CareBrief"],["Content Calendar","Calendar"],["Review & Approvals","Reviews"],["Asset Library","Assets"]];
const markets = ["Thousand Oaks","Westlake Village","Simi Valley","Calabasas","Camarillo","Moorpark","Ventura County","Los Angeles County"];
const items:Item[] = [...journalArticles.map(a=>({id:`j-${a.slug}`,title:a.title,type:"Journal",date:a.date,owner:"Eternal Life Hospice",status:"Needs review" as const,excerpt:a.description,source:a})),...emailCampaigns.map((e,i)=>({id:`e-${i}`,title:e.subject,type:"Email",date:e.sendDate,owner:"Eternal Studio",status:"Draft" as const,excerpt:e.preheader,emailIndex:i}))];
const pending = "Awaiting Source";

export default function Hub(){
 const [active,setActive]=useState("Overview"); const [open,setOpen]=useState("Executive"); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(""); const [notice,setNotice]=useState(""); const [selected,setSelected]=useState<Item|null>(null); const [statuses,setStatuses]=useState<Record<string,Item["status"]>>({});
 const currentGroup=groups.find(g=>g.items.some(i=>i[1]===active))?.name || (studio.some(i=>i[1]===active)?"Eternal Studio":"Operations");
 const setView=(v:string,g:string)=>{setActive(v);setOpen(g);setMobile(false)};
 const flash=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(""),2200)};
 const list=useMemo(()=>items.filter(i=>`${i.title} ${i.type}`.toLowerCase().includes(query.toLowerCase())),[query]);
 return <div className="hub-shell">
  <aside className={`hub-sidebar ${mobile?"is-open":""}`}><div className="hub-brand"><img src="/__reviews-mockup/elh-logo-stacked-cream-gold.png" alt="Eternal Life Hospice"/><button onClick={()=>setMobile(false)}><X size={17}/></button></div><div className="product-lockup"><span>Private executive BI</span><strong>Eternal Growth<br/>Intelligence</strong><small>Performance · Marketing · Census · Expansion</small></div>
   <nav>{groups.map(g=>{const Icon=g.icon;const expanded=open===g.name;return <div className="nav-group" key={g.name}><button className={`nav-group-trigger ${expanded?"expanded":""}`} onClick={()=>setOpen(expanded?"":g.name)}><Icon size={15}/><span><b>{g.name}</b><small>{g.sub}</small></span><ChevronDown size={13}/></button>{expanded&&<div className="nav-items">{g.items.map(([label,key])=><button className={active===key?"active":""} key={key} onClick={()=>setView(key,g.name)}>{label}</button>)}</div>}</div>})}</nav>
   <div className="sidebar-section"><div className="section-label">Eternal Studio <small>Create · Review · Publish</small></div>{studio.map(([label,key])=><button className={active===key?"active":""} key={key} onClick={()=>setView(key,"Eternal Studio")}><BookOpen size={14}/>{label}</button>)}</div>
   <div className="sidebar-section"><div className="section-label">Operations / data</div>{utility.map(([label,key])=><button className={active===key?"active":""} key={key} onClick={()=>setView(key,"Operations")}>{label}</button>)}</div>
   <div className="sidebar-foot"><span><i/> Connected sources only</span><button onClick={()=>flash("Workspace preferences are ready") }><Settings2 size={14}/> Workspace settings</button><div className="profile"><b>AD</b><span>Aleksandra D.<small>Founder & CEO</small></span></div></div>
  </aside>{mobile&&<button className="nav-scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
  <main className="hub-main"><header className="hub-topbar"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="crumb">Eternal Life / <strong>{currentGroup}</strong> / {active}</div><div className="top-actions"><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workspace"/></label><button className="icon-btn" onClick={()=>flash("No new reporting alerts")}><Bell size={17}/><i/></button><span className="top-avatar">AM</span></div></header>
   <section className="hub-content"><div className="page-heading"><div><span className="eyebrow">Connected-source truth <em/> {active==="Overview"?"Leadership view":"Private reporting workspace"}</span><h1>{titleFor(active)}</h1><p>{subtitleFor(active)}</p></div>{["Journal","Emails","CareBrief","Calendar","Assets"].includes(active)&&<button className="primary-btn" onClick={()=>flash("New Studio item workflow opened")}><Send size={14}/> New item</button>}</div>
   {active==="Overview"?<Executive onNavigate={setView}/>:active==="SEO"||active==="Website"?<Performance active={active}/>:active==="Connections"||active==="Health"||active==="ChangeLog"||active==="Definitions"?<Utility active={active}/>:active==="Expansion"||active==="HotZones"||active==="Opportunity"?<Expansion active={active}/>:active==="Attribution"?<Attribution/>:active==="Intelligence"?<Intelligence/>:active==="Census"||active==="CensusTrends"||active==="Referral"||active==="ReferralSources"||active==="PartnerMovement"?<Pending title={active==="Census"||active==="CensusTrends"?"Aggregate census reporting":"Referral performance reporting"} detail={active==="Census"?"Aggregate Census Data Source Required":"Referral Data Source Required"}/>:<Studio active={active} list={list} statuses={statuses} setStatuses={setStatuses} onOpen={setSelected}/>}
   </section></main>{selected&&<Detail item={{...selected,status:statuses[selected.id]||selected.status}} onClose={()=>setSelected(null)} onStatus={(s)=>{setStatuses({...statuses,[selected.id]:s});flash(`Moved to ${s}`)}}/>}{notice&&<div className="toast"><Check size={15}/>{notice}</div>}
 </div>
}
function titleFor(a:string){return ({Overview:"Executive overview",SEO:"SEO performance",Website:"Website performance",Connections:"Data connections",Health:"Reporting health",ChangeLog:"Website / SEO change log",Definitions:"KPI dictionary",Expansion:"Market overview",HotZones:"Growth Hot Zones",Opportunity:"Opportunity Zones",Attribution:"Attribution framework",Intelligence:"Intelligence brief",Census:"Census performance",CensusTrends:"Census trends",Referral:"Referral performance",ReferralSources:"Referral sources",PartnerMovement:"Partner movement",Journal:"Eternal Journal",Emails:"Email performance",CareBrief:"Eternal Care Brief",Calendar:"Content calendar",Reviews:"Review & approvals",Assets:"Asset library"} as Record<string,string>)[a]||a}
function subtitleFor(a:string){if(a==="Overview")return"Outcome → trend → driver → action. A concise leadership view with no unsupported business figures."; if(["Journal","Emails","CareBrief","Calendar","Reviews","Assets"].includes(a))return"Create, review and publish from Eternal Studio. Results remain in Growth Intelligence."; return "Measured reporting from connected sources only. Unsupported metrics remain clearly pending."}
function Executive({onNavigate}:{onNavigate:(v:string,g:string)=>void}){return <div className="page-stack"><div className="source-banner live"><ShieldCheck size={16}/><b>Reporting posture</b><span>Google Search Console and GA4 hooks retained. WhatConverts is connected to the website.</span><button onClick={()=>onNavigate("Connections","Operations")}>View source health <ArrowUpRight size={13}/></button></div><div className="metric-grid">{[["Current census",pending,"Aggregate source required"],["Admissions MTD",pending,"Reporting Feed Pending"],["Website calls",pending,"WhatConverts feed view"],["Organic search growth",pending,"Search Console trend required"]].map(([l,v,d])=><Metric key={l} label={l} value={v} detail={d}/>)}</div><div className="split-grid"><section className="panel"><Kicker>Enterprise performance</Kicker><h2>What leadership can act on now</h2><div className="outcome-row"><strong>Search visibility</strong><span>Connected</span><b>GA4 + Search Console</b></div><div className="outcome-row"><strong>Calls and conversions</strong><span>Partially connected</span><b>WhatConverts attribution</b></div><div className="outcome-row"><strong>Referral and census movement</strong><span>Awaiting Source</span><b>Non-PHI source required</b></div></section><section className="panel"><Kicker>Growth outlook</Kicker><h2>Attention without invention</h2><p className="quiet">The outlook will interpret connected trends after referral and aggregate census sources are confirmed. No fabricated opportunity scores or financial metrics are shown.</p><button className="text-btn" onClick={()=>onNavigate("HotZones","Expansion")}>Review Hot Zones <ArrowUpRight size={13}/></button></section></div><Pending title="Top referral sources and markets" detail="Reporting Feed Pending"/></div>}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Kicker({children}:{children:ReactNode}){return <span className="kicker">{children}</span>}
function Pending({title,detail}:{title:string;detail:string}){return <section className="panel pending"><Database size={24}/><Kicker>Source gate</Kicker><h2>{title}</h2><p>{detail}</p><span className="pending-pill">{detail}</span><small>No illustrative business values are displayed.</small></section>}
function Performance({active}:{active:string}){const [report,setReport]=useState<Report|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{fetch(`${import.meta.env.BASE_URL}api/elh-reporting?period=last28`).then(r=>r.json()).then(setReport).catch(()=>setReport({live:false,errors:["Reporting request unavailable"]})).finally(()=>setLoading(false))},[]);const m=report?.metrics;return <div className="page-stack"><div className={`source-banner ${report?.live?"live":""}`}><Activity size={15}/><b>{loading?"Connecting to Google reporting":report?.live?"Live Google reporting":"Reporting connection needs attention"}</b><span>{report?.live?"GA4 + Search Console · refreshed from connected endpoints":report?.errors?.[0]||"Reporting Feed Pending"}</span><button onClick={()=>location.reload()}><RefreshCw size={13}/> Refresh</button></div><div className="metric-grid">{[["Sessions",m?.sessions?.toLocaleString()||pending,"GA4"],["Search clicks",m?.searchClicks?.toLocaleString()||pending,"Search Console"],["Impressions",m?.impressions?.toLocaleString()||pending,"Search Console"],["Average position",m?m.averagePosition.toFixed(1):pending,"Search Console"]].map(x=><Metric key={x[0]} label={x[0]} value={loading?"Loading":x[1]} detail={x[2]}/>)}</div><div className="split-grid"><section className="panel chart-panel"><Kicker>{active==="SEO"?"Search Console":"GA4"} · last 28 days</Kicker><h2>{active==="SEO"?"Organic visibility":"Website discovery and action"}</h2><div className="bars">{(report?.trend||[]).map((p,i)=><i key={i} style={{height:`${Math.max(8,(p.sessions/Math.max(...(report?.trend||[{sessions:1}]).map(x=>x.sessions)))*100)}%`}}/>)}{!report?.trend?.length&&<span>{loading?"Loading connected trend":"Reporting Feed Pending"}</span>}</div></section><section className="panel"><Kicker>Measured dimensions</Kicker><h2>Useful next questions</h2><div className="action-list">{["Landing pages","Search queries","Keyword movement","Non-branded search growth","Local search performance"].map(x=><div key={x}><span>{x}</span><b>{m? "Available":"Pending"}</b></div>)}</div></section></div></div>}
function Expansion({active}:{active:string}){return <div className="page-stack"><div className="market-tabs">{markets.map(m=><button key={m}>{m}</button>)}</div>{active==="HotZones"?<><Zone title="Visibility Hot Zones" detail="Search impressions · clicks · local page performance · website traffic" status="Connected source layer"/><Zone title="Inquiry Hot Zones" detail="Website calls · WhatConverts attribution · website leads where available" status="Connected where attribution exists"/><Zone title="Growth Hot Zones" detail="Referrals · evaluations · admissions · census contribution" status="Awaiting Referral / Census Data"/></>:active==="Opportunity"?<Zone title="Opportunity Zones" detail="Demand signals with weak Eternal capture: high visibility + low calls, rising impressions + weak ranking, strong traffic + weak conversion." status="Calculated only from connected sources"/>:<section className="panel"><Kicker>Market coverage</Kicker><h2>Geography without invented scores</h2><p className="quiet">Search Console, GA4 and WhatConverts can contribute where geography or landing-page attribution exists. Referral and census fields remain Awaiting Source until connected.</p><div className="market-table">{markets.map(m=><div key={m}><b>{m}</b><span>Search visibility <em>Connected</em></span><span>Website traffic <em>Connected</em></span><span>Referrals <em>Awaiting Source</em></span><span>Admissions <em>Awaiting Source</em></span></div>)}</div></section>}</div>}
function Zone({title,detail,status}:{title:string;detail:string;status:string}){return <section className="panel zone"><div><Kicker>Expansion layer</Kicker><h2>{title}</h2><p>{detail}</p></div><span className="pending-pill">{status}</span><button className="icon-btn"><ChevronRight size={17}/></button></section>}
function Attribution(){return <div className="page-stack"><section className="panel"><Kicker>Measured → partially attributed → awaiting connection</Kicker><h2>Attribution framework</h2><div className="path"><span>Source</span><ChevronRight/><span>Interaction</span><ChevronRight/><span>Lead</span><ChevronRight/><span>Referral</span><ChevronRight/><span>Evaluation</span><ChevronRight/><span>Admission</span><ChevronRight/><span>Census</span></div><div className="attribution-row"><b>Google Search → Website → WhatConverts Call</b><span className="tag measured">Measured example</span></div><div className="attribution-row"><b>Referral → Admission</b><span className="tag pending-tag">Awaiting Connection</span></div><div className="attribution-row"><b>Email → Journal Article → Website Call</b><span className="tag partial">Partially Attributed</span></div></section></div>}
function Intelligence(){return <div className="intelligence-grid">{[["WINS","No connected win signals yet","Wins will trace to real Search Console, GA4, WhatConverts or future pipeline data."],["WATCH","Traffic and calls","Traffic rising while calls remain flat will appear only when both feeds are present."],["OPPORTUNITY","Demand with weak capture","Market visibility, rankings and conversion will be compared without invented scores."]].map(x=><section className="panel insight" key={x[0]}><Kicker>{x[0]}</Kicker><h2>{x[1]}</h2><p>{x[2]}</p><span className="pending-pill">Awaiting connected comparison</span></section>)}</div>}
function Utility({active}:{active:string}){if(active==="Definitions")return <section className="panel dictionary"><Kicker>Data definitions</Kicker><h2>KPI dictionary</h2>{[["Organic CTR","Search Console","Clicks ÷ Impressions","Refresh with search reporting"],["Referral-to-Admission Conversion","Future Referral Pipeline","Admissions from referrals ÷ qualified referrals","Source required"],["Net Census Change","Future Census Feed","Ending census − beginning census","Aggregate source required"]].map(x=><div className="dict-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><span>{x[2]}</span><small>{x[3]}</small></div>)}</section>;if(active==="ChangeLog")return <section className="panel"><Kicker>Change governance</Kicker><h2>Website / SEO change log</h2><p className="quiet">Meaningful changes made by Eternal or Thryv should be visible here before performance interpretation begins.</p><div className="log-form">{["Date","URL / Page","Change","Reason","Keyword / Business Objective","Team Responsible","Expected Result","Validation","Notes"].map(x=><label key={x}>{x}<input placeholder="Awaiting entry"/></label>)}</div><button className="primary-btn">Add change record</button></section>;return <div className="page-stack"><section className="panel"><Kicker>{active==="Health"?"Source health":"Authoritative connections"}</Kicker><h2>{active==="Health"?"Reporting health":"Data connections"}</h2><div className="connection-list">{[["Google Search Console","Connected / Available","Organic search intelligence"],["GA4","Available / confirm dashboard ingestion","Website traffic and engagement"],["WhatConverts","Connected to Website","Call tracking and attribution"],["Google Business Profile","Connected through Thryv","Connected — Reporting Feed Pending"],["Social accounts","Connected through Thryv","Reporting Feed Pending"],["Email platform","Performance Feed Required","Results only in Growth Intelligence"],["Referral pipeline","Data Source Required","No PHI required"],["Census","Aggregate Data Source Required","Non-PHI reporting only"],["Advertising","Awaiting Source","No paid media feed connected"]].map(x=><div className="connection-row" key={x[0]}><CircleDot size={14}/><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></section></div>}
function Studio({active,list,statuses,setStatuses,onOpen}:{active:string;list:Item[];statuses:Record<string,Item["status"]>;setStatuses:(x:Record<string,Item["status"]>)=>void;onOpen:(x:Item)=>void}){const filtered=list.filter(i=>active==="Reviews"?i.status==="Needs review":active==="Journal"?i.type==="Journal":active==="Emails"?i.type==="Email":true);return <section className="panel studio-list"><div className="studio-intro"><BookOpen size={20}/><div><Kicker>Eternal Studio · Create / Review / Publish</Kicker><h2>{active==="Reviews"?"Review queue":"Production workspace"}</h2></div></div>{filtered.slice(0,12).map(i=><button className="studio-row" key={i.id} onClick={()=>onOpen(i)}><FileText size={16}/><span><b>{i.title}</b><small>{i.type} · {i.date}</small></span><em>{statuses[i.id]||i.status}</em><ChevronRight size={15}/></button>)}{!filtered.length&&<div className="empty-state"><FileCheck2 size={25}/><b>No items in this Studio view</b><span>Production records will appear here.</span></div>}</section>}
function Detail({item,onClose,onStatus}:{item:Item;onClose:()=>void;onStatus:(s:Item["status"])=>void}){return <div className="detail-backdrop" onClick={onClose}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><header><div><Kicker>{item.type}</Kicker><h2>Studio item</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></header><div className="detail-body"><span className="tag">{item.status}</span><h1>{item.title}</h1><p>{item.excerpt}</p><div className="meta-grid"><span>Owner<b>{item.owner}</b></span><span>Date<b>{item.date}</b></span></div><div className="preview-paper"><Kicker>Editorial preview</Kicker><h3>{item.title}</h3><p>{item.excerpt}</p></div><div className="detail-actions"><button className="primary-btn" onClick={()=>onStatus(item.status==="Needs review"?"Approved":"Needs review")}><Check size={14}/>{item.status==="Needs review"?"Approve":"Return to review"}</button><button className="secondary-btn" onClick={()=>onStatus(item.status==="Scheduled"?"Draft":"Scheduled")}><CalendarDays size={14}/>{item.status==="Scheduled"?"Move to draft":"Schedule"}</button></div></div></aside></div>}